### ISSUE TITLE
Use :set on the defcustoms instead of add-variable-watcher

### ISSUE THREAD

**Issue by minad** [jdtsmith/kind-icon#1]
`:set` is the mechanism to execute code if custom variables are changed. `add-variable-watcher` is more of a debugging feature as I see it. Note that you cannot use `setq` on the variable then, or additionally have to flush the cache afterwards. But as long as you go via the customization interface or custom sections of `use-package` it will work well.

**Comment by minad** [comment]
Why do you reset the cache in `kind-icon-enhance-completion` btw?

**Comment by minad** [comment]
Ping @jdtsmith

**Comment by jdtsmith** [comment]
This is to support the customize interface.  Since icons are cached with styling, this allows users to change icons/faces/etc. and immediately have them applied.

**Comment by minad** [comment]
What do you mean? The variable watchers?

**Comment by jdtsmith** [comment]
Yes.  Try this: `M-x customize-variable kind-icon-mapping`.  Go to a code buffer, start a completion. Change your customize (e.g. make the `variable` icon `duck`).   Apply the customization and switch back to your code buffer.

**Comment by jdtsmith** [comment]
> Why do you reset the cache in `kind-icon-enhance-completion` btw?

Basically for safety.  One issue with the cache is if you change font size, the cached icons are the wrong size.  So if the user explicitly re-wraps their completion function, I thought it was worth invalidating the local cache and rebuilding.  FYI, svg-lib maintains its own on-disk cache, which is not invalidated (but of course has no styling/padding).

**Comment by minad** [comment]
Did you try the `:set` property of `defcustom`. This should give you the behavior you are looking for in the customize interface. Using a variable watcher is definitely wrong. I've grepped over the emacs codebase and it is used nowhere and I've also never seen it used anywhere. Personally I've only used it for debugging purposes.

**Comment by jdtsmith** [comment]
Good idea.  The advantage of a var-watcher is even programatic changes to the variable trigger it, but probably not worth the smell of lingering debug code.  Updated to `:set` in f6de892.

**Comment by minad** [comment]
> The advantage of a var-watcher is even programatic changes to the variable trigger it.

Yes, but this is a long debate. Many people say that using `setq` on customizable variables is wrong for this reason, and I tend to agree. I use a `setq!` helper in my init.el

~~~ elisp
(defun setq! (var val)
  (funcall (or (get var 'custom-set) #'set-default) var val))
~~~
