### ISSUE TITLE
The icons overlap on line numbers at left border

### ISSUE THREAD

**Issue by Eason0210** [jdtsmith/kind-icon#11]
Hi @jdtsmith ,

Thanks for this  great package.
I use it with corfu, but when the completion popup window is close to the border, the icon will overlap on the line numbers. Is this by design? Is there options to avoid it?

<img width="656" alt="image" src="https://user-images.githubusercontent.com/47546452/149665222-9622b228-f684-481d-8676-05a79e514531.png">

**Comment by jdtsmith** [comment]
The alignment is provided by corfu, and is designed to line completions up under text in the buffer.   In fact the corfu popup buffer can lie atop multiple windows, in the mini-buffer, etc.   If you prefer an in-buffer completion UI, company is probably the way to go.

**Comment by Eason0210** [comment]
Thanks for your advice. 

I just moved from company, because it play not very good with eglot. see detail here at the[ eglot discusion](https://github.com/joaotavora/eglot/discussions/807)

so it is designed, I will try to adapt to this new UI. Thanks again.
