### ISSUE TITLE
Autoload kind-icon-margin-formatter and kind-icon-enhance-completion

### ISSUE THREAD

**Issue by daanturo** [jdtsmith/kind-icon#14]
Having them autoloaded should be nice.

**Comment by jdtsmith** [comment]
Can you share how you have configured kind-icon to need these?

**Comment by daanturo** [comment]
I don't use `use-package`, currently my config looks like this:
```lisp
(require 'kind-icon)
(setq kind-icon-default-face 'corfu-default)
(add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter)
```
Autoloading can free the `require` call; also it provides a way to check, without loading, if `kind-icon` is installed `(fboundp 'kind-icon...)` when the package isn't installed through `package.el` (no `package-installed-p`).

In addition, it helps lazy loading: just `(add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter)`  can defer loading `kind-icon` until `corfu`'s completion list appears.

**Comment by jdtsmith** [comment]
Added in 03a4082.  Can you check that they are working with your config?

**Comment by daanturo** [comment]
Thank you for this!
