### ISSUE TITLE
FR: Add a function for manually install all the preset svg icons

### ISSUE THREAD

**Issue by Eason0210** [jdtsmith/kind-icon#15]
Hi @jdtsmith ,

Thanks for make this excellent package.

Recently, after I installed the `svg-lib` to enable  the svg-icons, every time I input a new keyword, I have to wait for downloading an icon, especially sometimes the network is not good and it takes a long time to wait. It's kind of annoying.

It would be nice to add a function that the user can trigger manually to download all the preset icons to the cache directory.
Or we can provide a repository which include only the preset icons, then user can download from it manually.

**Comment by jdtsmith** [comment]
Sounds like you have svg-lib misconfigured.  It does download and cache icons in the directory specified by `svg-lib-icons-dir`, so that simply showing them _once_ will result in never downloading again.  Do you have such a directory and is it populated with SVG icons?

**Comment by jdtsmith** [comment]
Also, it's easy to double-check if this is working using M-x customize-group kind-icon, open the mapping and Preview each icon.

**Comment by Eason0210** [comment]
> Sounds like you have svg-lib misconfigured. It does download and cache icons in the directory specified by `svg-lib-icons-dir`, so that simply showing them _once_ will result in never downloading again. Do you have such a directory and is it populated with SVG icons?

Yes, It will download only one icons in the` ~/.emacs.d/.cache/svg-lib` directory. 
For example, when I input `(mes` first time in emacs-lisp-mode, only get one icon downloaded, is this behavior correct?
I expect it to download all the icons( Actually 32 icons in total).
<img width="763" alt="image" src="https://user-images.githubusercontent.com/47546452/167327575-1780ef2c-df44-4fae-b312-ba8dd17780e4.png">

> Also, it's easy to double-check if this is working using M-x customize-group kind-icon, open the mapping and Preview each icon.

Click the preview button will trigger the icon to download, but user need to click 32 times. 
Any way, it works 😄  Thank you.

```emacs-lisp
(use-package kind-icon
  :after corfu
  :custom
  (kind-icon-default-face 'corfu-default)
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
```

**Comment by jdtsmith** [comment]
It only downloads _on demand_, i.e. when an icon is missing from the cache.  This could be because you just started using kind-icon, or configured a new icon.  Here you only have one type of completion, so only one will have been downloaded.  But eventually all would have been retrieved as you use it.  And forever after that, no need to download again.  

I'll consider an icon-preview that will have the effect of downloading them all; will leave this open for a bit to see whether that materializes.

**Comment by Eason0210** [comment]
> It only downloads on demand.

Ok, now I understand.

> I'll consider an icon-preview that will have the effect of downloading them all

It would be great 👍

**Comment by jdtsmith** [comment]
Please see latest commit ee51d05 and give a try.

**Comment by Eason0210** [comment]
Great, It works well.

After I run <kbd>M-x</kbd> `kind-icon-preview-all` and got this nice preview result:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/47546452/167743843-b7c435a4-e30c-4314-941f-30bc677c0df2.png">
