### ISSUE TITLE
don't blend right-pad 2 char's background in terminal

### ISSUE THREAD

**Issue by eki3z** [jdtsmith/kind-icon#17]
In commit f9d803cc12a9406e7d7981f7ab3c065576055202, added space after text icon in terminal, however, when `kind-icon-blend-background` is `t`, the added space's background is blended too. could you fix it ?

**Comment by jdtsmith** [comment]
I see you closed this, is it still an issue?  If so, can you post a screenshot of what you mean?  The space around the text/icon are indeed blended on purpose.

**Comment by eki3z** [comment]
@jdtsmith emm.., I thought it's a bug at first, however it's no big deal. Don't blend the space would be better, in my opinion.
