### ISSUE TITLE
The last candidate will be cut when using svg-icons on Windows system

### ISSUE THREAD

**Issue by Eason0210** [jdtsmith/kind-icon#18]
Hi @jdtsmith 

When I use`kind-icon` with`Corfu` on Windows system, the popup window can't show all the icons, the last candidate will be cut.
This issue only happen on Windows system, but with different fonts will have different result. 
I only test these fonts:  `SF Mono` , ` Cascadia Mono` and  `Consolas`

Using `SF Mono`, the last candidate is cut, and the candidates only have 9 lines, expected is 10:

![image](https://user-images.githubusercontent.com/47546452/170429615-a81586dd-67bf-43b6-815e-01fc55edf79f.png)

Using` Consolas`, the candidates have 10 lines, but the last candidate is cut:

![image](https://user-images.githubusercontent.com/47546452/170427907-8d6f1b77-9e8d-4dbe-84ae-975d76812806.png)

Using` Cascadia Mono`, the result looks good , but the candidates only have 9 lines, expected is 10:

![image](https://user-images.githubusercontent.com/47546452/170429068-41bd1211-fb01-41f4-80b7-f8afca7040c2.png)

If I use the text-based icon, It works well.

Steps to reproduce:
1. Create an init.el file in `~/.emacs.d/init.el`
2. Put the following code in the` init.el` file
```emacs-lisp
;;(add-to-list 'default-frame-alist (cons 'font "Consolas-11"))
;;(add-to-list 'default-frame-alist (cons 'font "Cascadia Mono-11"))
(add-to-list 'default-frame-alist (cons 'font "SF Mono-11"))

;; Setup corfu
(package-install 'corfu)
(require 'corfu)
(setq corfu-auto t)
(global-corfu-mode 1)

;; Setup kind-icon
(package-install 'kind-icon)
(require 'kind-icon)
(setq kind-icon-default-face 'corfu-default)
(add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter)
```
3. Start Emacs, It will install `Corfu` and `kind-icon` , aslo the dependency `svg-lib`
4. Try to input someting on` *scratch*` buffer, you will see the result.

Actually, I'm not sure if the problem is caused by`Kind-icon`, may be it is caused by`Corfu`.

Emacs 29.0.50 https://github.com/emacs-mirror/emacs/commit/aab560f0c1955bae57cc35a71be95b5bfa2ab525

**Comment by jdtsmith** [comment]
I don't have Windows to test, but one issue is that icons are rendered and cached.  So if you change the font, you should `M-x kind-icon-reset-cache` to get an accurate idea.   What this _may_ do, however, is demonstrate that the problem happens for all fonts.   

If that is the case, it's probably then a bug in `svg-lib` rendering of full height icons.  Or, perhaps your Emacs is confused about its `(window-font-height)` (misleading `svg-lib`).

You should be able to work around this by reducing the `:height` in `kind-icon-default-style` to something smaller, like 0.8.  Give that a try.

**Comment by Eason0210** [comment]
> You should be able to work around this by reducing the `:height` in `kind-icon-default-style` to something smaller, like 0.8. Give that a try.

Thanks for you advice. I tried to customize the `:height` to 0.9 and it works well now.
```emacs-lisp
(custom-set-variables
 '(kind-icon-default-style
   '(:padding 0 :stroke 0 :margin 0 :radius 0 :height 0.9 :scale 1.0))
 '(package-selected-packages '(kind-icon corfu)))
```
Using the font `SF Mono`
![image](https://user-images.githubusercontent.com/47546452/170549310-2862490b-d44d-4e6f-8854-5ba9a114675d.png)
