### ISSUE TITLE
kind-icon 0.1.5 in GNE ELPA differs tag of 0.1.5.

### ISSUE THREAD

**Issue by buzztaiki** [jdtsmith/kind-icon#20]
https://github.com/jdtsmith/kind-icon/releases/tag/0.1.5 has [autoload cookie](https://github.com/jdtsmith/kind-icon/blob/0.1.5/kind-icon.el#L286), but https://elpa.gnu.org/packages/kind-icon-0.1.5.tar does not have it.

**Comment by buzztaiki** [comment]
I would be happy to have a new release.

**Comment by jdtsmith** [comment]
Thanks for the reminder, 0.1.6 released.

**Comment by buzztaiki** [comment]
Thank you! I was able to use autoloading in the latest release.
