### ISSUE TITLE
some mode such as eshell-mode can not add icons.

### ISSUE THREAD

**Issue by haoisli9** [jdtsmith/kind-icon#21]
kind-icons use "company-kind" to get the completing-function, but some mode such as eshell-mode does not have company-kind property. so it can not get icons. how to add icons in eshell-mode. and some other mode that does not have "company-kind" function?

**Comment by jdtsmith** [comment]
The main issue is, how can you know what _kind_ a given candidate is?  If you can write an elisp function that can return kind somehow based just on the candidate, you could use [cape](https://github.com/minad/cape) and  `cape-wrap-properties` to add it.  If that sounds like too much, you should open an issue/request a feature upstream.
