### ISSUE TITLE
kind-icon-preview fails

### ISSUE THREAD

**Issue by elkarouh** [jdtsmith/kind-icon#24]
I am unable to view the icons:
I get a series of messages

 Warning (emacs): Error retrieving icon format-list-checks, falling back on short-text
(http/80 nodename nor servname provided, or not known)

I am at home with a working internet connection.

**Comment by jdtsmith** [comment]
Sounds like an issue with svg-lib or your network config.  Did this persist?

**Comment by jdtsmith** [comment]
Closing for now.  Let me know if you track this down to a problem with kind-icon but appears to be a network or svg-lib.
