### ISSUE TITLE
wrong-number-of-arguments

### ISSUE THREAD

**Issue by avi0010** [jdtsmith/kind-icon#25]
![Screenshot_2022-10-09-03-03-14_1920x1080](https://user-images.githubusercontent.com/54092865/194728545-67600bf4-4c42-46fe-bd48-c4321a2db8d4.png)

**Comment by jdtsmith** [comment]
Looks like a misconfigured mapping variable.  In the buffer where this happens, `M-:` then `(assq 'text kind-icon-mapping)[Ret]` and report the result.

**Comment by avi0010** [comment]
`(text "tx" :icon "script-text-outline" :face shadow)`

**Comment by jdtsmith** [comment]
Looks fine.  Now try `(face-attribute 'shadow :foreground nil t)`.

**Comment by avi0010** [comment]
Evaluates to unspecified.

**Comment by jdtsmith** [comment]
> Evaluates to unspecified.

This is the problem.  What version of emacs?  The default `shadow :foreground` for me (emacs -Q, vs 28.2) is "grey70".  Please try from "emacs -Q".  If that works, your theme must have overridden this face. 

I have pushed a change which should work around this so at least it doesn't error.  Give it a try.  But you won't get any special colors for this kind.

You can also configure `kind-icon-mapping` to use another face whose foreground is not unspecified, or try another theme.   `M-x list-faces-display` for all your configured faces.

**Comment by avi0010** [comment]
That solved the issue mate, appreciate the help.
