### ISSUE TITLE
Blend background doesn't work with cape-dabbrev

### ISSUE THREAD

**Issue by konrad1977** [jdtsmith/kind-icon#26]
When I am trying to auto-complete cape-dabbrev i got an error:

`"Error in post-command-hook (corfu--post-command): (wrong-number-of-arguments #<subr color-rgb-to-hex> 0)"`

```
(use-package kind-icon
  :after corfu
  :custom
  (kind-icon-default-face 'corfu-default) ; to compute blended backgrounds correctly
  (kind-icon-use-icons nil)
  (kind-icon-blend-background t)
  (kind-icon-blend-frac 0.15)
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

```
If I turn off `(kind-icon-blend-background nil) `it work as expected.

**Comment by jdtsmith** [comment]
This has nothing to do with cape-dabbrev, but probably this means that the `'kind` it provides (`text`) has a face specified in `kind-icon-mapping` that has no foreground.  For whatever reason lots of themes do this.  By default this face is `shadow`, but I have now removed that.  See also #25.  Update to 0.1.8 for the fix.

**Comment by konrad1977** [comment]
Thanks for the explanation. I upgraded to 0.18 - its still the same issue, you are still referring to shadow in 0.18, even if you commit says different. Did you submit the wrong version to melpa?

**Comment by jdtsmith** [comment]
It's not on MELPA it's on ELPA.  Please try it from the master branch and let me know if it is working.

**Comment by jdtsmith** [comment]
OK I have added even more defense against 'unspecified and bumped to 0.1.9 which should fix this once and for all. Feel free to comment again if not.

**Comment by konrad1977** [comment]
Thanks, will try when it reaches Elpa. Added :foreground color to my themes now instead. I must say I really love kind-icon, thanks for making the package @jdtsmith
