### ISSUE TITLE
Icons colorization

### ISSUE THREAD

**Issue by ceed0** [jdtsmith/kind-icon#27]
First, thanks for the great package.

Do you think it would be possible to colorize icons for certain variables with colors associated with them, like on the screenshot from [here](https://github.com/tailwindlabs/tailwindcss-intellisense#features)
![ss](https://raw.githubusercontent.com/bradlc/vscode-tailwindcss/master/packages/vscode-tailwindcss/.github/autocomplete.png)

**Comment by jdtsmith** [comment]
In principle but where would the information on what “color” a variable is come from? The colors are chosen to replicate font lock colors in the buffer for variables vs functions etc.

**Comment by ceed0** [comment]
That would be mode dependant, for emacs itself :foreground/:background values could be used for faces. 
LSP-servers can send this info through eglot or lsp-mode. But I'm not sure how kind-icon could receive this information.

**Comment by jdtsmith** [comment]
What would be needed is a backend property like `:kind-color` or similar that modes provide.  Kind-icon doesn't know much about the competitions it is showing other than what it's told.  Closing, but if something develops along these lines we can revisit.
