### ISSUE TITLE
Example how to change icons?

### ISSUE THREAD

**Issue by konrad1977** [jdtsmith/kind-icon#31]
Thanks for a great package.
How do I change the icons to _octicon_ or _vscode_?
I saw that there is `kind-icon-default-style` and `kind-icon-default-style` but I dont understand how to change the icons?

**Comment by konrad1977** [comment]
Got it working.

**Comment by jdtsmith** [comment]
OK good.  Just heed the warning about monochrome-only icons.

**Comment by minikN** [comment]
Could someone help me on this?
I added `:collection "octicon"` to `kind-icon-default-style` via `customize-variable`:

![image](https://github.com/jdtsmith/kind-icon/assets/1888338/e5cb2148-f08b-457b-9686-1f86d0df4203)

But this doesn't work, I get:
```
Warning (emacs): Error retrieving icon function, falling back on short-text (stringp nil)
```

**Comment by jdtsmith** [comment]
Did you actually change `kind-icon-mapping` to include valid icons from the [octicon](https://primer.style/foundations/icons) collection?
