### ISSUE TITLE
Allow blending background on terminal frames

### ISSUE THREAD

**Issue by mohkale** [jdtsmith/kind-icon#32]
Hi, 

It looks you explicitly [prevent blending](https://github.com/jdtsmith/kind-icon/blob/67ead8eddc5824a0cdbc34d68102c271b2ab93b0/kind-icon.el#L313) the of the background color and the kind-icon foreground on terminal frames. Could you clarify why? I'd like to have this supported and just removing the not terminal check fixes it for me as I'd expect.

**Comment by jdtsmith** [comment]
Interesting.  Not sure why I disabled that.  Would you like to submit a PR?

**Comment by jdtsmith** [comment]
Can you post a picture of it working in terminal?  I wonder if you've tried a [NerdFont](https://github.com/rainstormstudio/nerd-icons.el#use-nerd-icons-with-corfu) in the terminal with kind-icon?

**Comment by mohkale** [comment]
@jdtsmith 

> Can you post a picture of it working in terminal?

Sure.

![Screenshot_20230506_190741](https://user-images.githubusercontent.com/23294780/236640061-f9c06401-42ef-456c-8b56-a0751148503b.png)

> I wonder if you've tried a [NerdFont](https://github.com/rainstormstudio/nerd-icons.el#use-nerd-icons-with-corfu) in the terminal with kind-icon?

I haven't yet. For reference I maintain [all-the-icons-nerd-fonts](https://github.com/mohkale/all-the-icons-nerd-fonts) and have been using nerd icons in terminal frames for a while but not with this relatively new nerdfont package. I might consider using it eventually but for now I use consistent text and graphic icons on completion UIs.

**Comment by jdtsmith** [comment]
Thanks.  If you scroll down they have a config for kind-icon usage.
