### ISSUE TITLE
Interaction between kind-icon and ement causes breakage

### ISSUE THREAD

**Issue by stsquad** [jdtsmith/kind-icon#37]
It looks like some sort of interaction between ement (a matrix client) and kind-icon causes breakage. I suspect it is due to the way they use svg-lib. See https://github.com/alphapapa/ement.el/issues/212 for the full details.

**Comment by jdtsmith** [comment]
Looks complicated.  Can you briefly describe the issue?  Is it clear what's causing it?

**Comment by alphapapa** [comment]
> Looks complicated. Can you briefly describe the issue? Is it clear what's causing it?

You'll have to read through the linked issue.  And, no, it's not clear at all.  In fact, the error seems inexplicable, and I can't reproduce it.  @stsquad says that it only happens when he uses the `kind-icon` configuration he shows there, but I don't know how that could cause it, either.

**Comment by jdtsmith** [comment]
That's a lot to digest; @stsquad can you make a minimum reproducer starting from emacs -q, ideally using _just_ an `svg-lib-tag` call (not all of ement)?   Often I've found that bisecting configs gives you the wrong impression about the source of the error.  It could also be a bug in svg-lib, for example.

Also if you `C-M-x` inside `svg-lib-tag`, the error traceback will be more specific.  I've seen no issues with this, in the same buffer where `kind-icon` is operating:

```elisp
(insert-image (svg-lib-tag "n" nil :background "#d98580" :foreground "white" :stroke 0))
```

**Comment by jdtsmith** [comment]
It seems this is a problem with conflicting svg tag libraries?  Let me know if kind-icon is implicated on further study.
