### ISSUE TITLE
Icon's too big making candidates not show fully.

### ISSUE THREAD

**Issue by cronyakatsuki** [jdtsmith/kind-icon#40]
Hello, I have recently faced the issue where the size of the kind icon's makes it so completion candidates in corfu end up not fully shown like in the next couple screenshots.

> first screnshot
![pic-selected-231125-1453-06](https://github.com/jdtsmith/kind-icon/assets/64900606/88e9e9e4-9350-467d-9f7f-973b9893207b)

Here we can see that nineth candidate is just barelly visible.

> second screenshot
![pic-selected-231125-1458-11](https://github.com/jdtsmith/kind-icon/assets/64900606/50a5ea89-acd9-4a46-8099-a9cb6b583e8f)

Here I have selected last candidate and as shown in the screenshot, it doens't show in popup as seen.

> third screenshot
![pic-selected-231125-1500-03](https://github.com/jdtsmith/kind-icon/assets/64900606/785ef400-a334-4494-9139-3a25a3e1f88e)

Here I selected the candidate before the last one, that's barelly visiblel.

This issue also happens with default emacs, just that the last candidate is half visible with icons.

> settings related to kind icon
``` emacs-lisp
(use-package kind-icon
   :ensure t
   :after corfu
   :custom
   (kind-icon-default-face 'corfu-default) ; Have background color be the same as `corfu' face background
   :config
   (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter)) ; Enable `kind-icon'
```

**Comment by cronyakatsuki** [comment]
The issue mostly happens on higher font sizes

**Comment by cronyakatsuki** [comment]
Fixed the issue by changing the icon size, sorry for the issue.

**Comment by jdtsmith** [comment]
Is this an issue with corfu drawing a large enough child frame?

**Comment by cronyakatsuki** [comment]
From what I saw it isn't, without the icons the issue doesn't happen and on lower font size, like below <7 it also doesn't happen with icons enabled.

It might be also be a problem with my font, but at the same time the same thing happens even when I use the default font.

For now I have lowered the icon size to 0.8 and it works with no problems now.
