### ISSUE TITLE
Invalid face attribute :background nil

### ISSUE THREAD

**Issue by danielpopescu** [jdtsmith/kind-icon#41]
MacOS, 29.1, native compilation. Using latest corfu, kind-icon I get a lot of messages:
Invalid face attribute :background nil
whenever completion at point is invoked...
 
Using kind-icon as:
 
(require 'kind-icon)
(use-package kind-icon
  :after corfu
  :custom
  (kind-icon-use-icons t)
  (kind-icon-default-face 'corfu-default) ; Have background color be the same as `corfu' face background
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter) ; Enable `kind-icon'
  )

If I stop using kind-icon the messages go away.

Thanks!

**Comment by jdtsmith** [comment]
Can you `M-x toggle-debug-on-error` and post the traceback?  You may have in incompatible version of svg-lib and need to update.

**Comment by noblekid96** [comment]
I am experiencing the same issue. Using emacs-mac 29.1 with Doom Emacs framework.

I have kind-icons 0.2.1 installed and svg-lib 0.3 installed

**Comment by danielpopescu** [comment]
> Can you `M-x toggle-debug-on-error` and post the traceback? You may have in incompatible version of svg-lib and need to update.

I did, but debug trace is not triggered.
I do have the very latest everything: corfu(20240103.1401), kind-icon(0.2.1.0.20231217.93534), svg-lib (0.3.0.20240104.62538).  

Also, if I evaluate: M-: (insert-image (svg-lib-tag "TODO"))
in my scratch buffer, I do not see any error messages. I guess svg-lib on its own seems fine...

**Comment by jdtsmith** [comment]
Fixed in d8e73fe; please report back.
