### ISSUE TITLE
Sly completion via Corfu and kind-icons doesn't show icons

### ISSUE THREAD

**Issue by mdbergmann** [jdtsmith/kind-icon#43]
Hello.

This is an inquiry only basically, because I can't seem to get icons for completions in Sly (Common Lisp).
Sly seems to deliver the 'kind' but there are no icons. However, in ELisp it works well.
Can you imagine where I'd need to have a look to troubleshoot?

Thanks
<img width="389" alt="Bildschirmfoto 2024-03-22 um 16 33 50" src="https://github.com/jdtsmith/kind-icon/assets/2143978/e17c3591-72cc-4a30-b6ab-3dea71a85ada">

**Comment by jdtsmith** [comment]
The CAPF in question must implement `:company-kind` metadata: a function that takes the completion and returns its kind.  Taking a look, it seems after a few wrappers `sly--completions-complete-symbol-1` is the relevant CAPF.  It does not implement `:company-kind`.  You could request it get added there (but the mode needs to actually have the data of course).

**Comment by mdbergmann** [comment]
Thanks for checking.
