### ISSUE TITLE
With cape.el: `Error in post-command-hook (corfu--post-command): (error "Invalid face" :icon)`

### ISSUE THREAD

**Issue by polaris64** [jdtsmith/kind-icon#7]
I've just been trying the new [cape.el](https://github.com/minad/cape) with Corfu and when trying to complete a filename I get the error detailed in the issue title. If I remove `kind-icon-margin-formatter` from `corfu-margin-formatters` then the issue disappears.

I'm using the following versions: -

  - Corfu: 622be5266b5e9ebb85327103d66200f1860f9e1b
  - cape.el: 26b822db0aa99752294e4e319b0e76cde601e258
  - kind-icon: 550ac23b8f85a74efd7fd7fdcaaf3eab19fbdeeb

**Comment by inigoserna** [comment]
The error comes from line #93:
`(file "f" :face :icon "file-document-outline" font-lock-string-face)`

":face" is misplaced there.

Maybe kind-icon (and/or corfu) should check for valid entries?

Thanks @jdtsmith and @minad for these packages!

**Comment by minad** [comment]
ind-icon bug?

**Comment by polaris64** [comment]
Yes, I just fixed the line identified by @inigoserna and I can confirm that it works

**Comment by inigoserna** [comment]
> kind-icon bug?

More a typo than a bug, imo.

But I think corfu or kind-icon should check for valid values.

**Comment by jdtsmith** [comment]
Thanks, corrected in d6c71a1.

**Comment by tsdh** [comment]
Could you make a bugfix release on ELPA?

**Comment by jdtsmith** [comment]
It should have been updated several weeks ago.  Just in case I bumped the version.

**Comment by tsdh** [comment]
Yeah, I think ELPA requires a new version number in order to make a new release. Thank you!

**Comment by jdtsmith** [comment]
1.1.3 is published on ELPA, thanks for the reminder.
